### ISSUE TITLE
手順 2 についての質問です。

### ISSUE THREAD

**Issue by kozaru** [maepon/markup-code-set#1]
教えてください。

手順１、３で TEST と表示されるHTMLをブラウザで確認できたんですが、２の編集はどこか編集する箇所があるんでしょうか？

（DoorKeeperでは公開してないですが、10/14参加予定です）

**Comment by maepon** [comment]
説明不足ですいません。
ディレクトリの構成が変わったりしない場合は編集なしでそのままで大丈夫です。
（README編集しました）

a4ed54da8015a08e85cb571c9d9a77f2ad0715d0

**Comment by kozaru** [comment]
承知しました。ありがとうございました！
